### ISSUE TITLE
Mutable return values

### ISSUE THREAD

**Issue by tzoiker** [sirkonst/async-reduce#3]
Does it make sense to return some read-only proxy instead of the real return value? Otherwise, there may be hard-to track errors because of inattentiveness.

**Comment by sirkonst** [comment]
Do you know universal read-only proxy for all python objects? ;-)

I going to add remark about mutable values to caveats.

**Comment by tzoiker** [comment]
That's why I didn't suggest anything :)

Adding remark seems legit.

**Comment by sirkonst** [comment]
Readme has been updated.
